version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
        POSTGRES_USER: ${POSTGRES_USER:-1234}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1234}
        PGDATA: /data/postgres
    ports:
      - "5432:5432"